# Generated by Django 3.2.6 on 2021-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coronaApp', '0002_delete_coronadate'),
    ]

    operations = [
        migrations.CreateModel(
            name='coronaDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('confirmed', models.IntegerField(default=0)),
            ],
        ),
    ]
