# Generated by Django 3.2.6 on 2021-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0003_coronadate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronadate',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
