# Generated by Django 3.2.6 on 2021-09-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0005_coronadistrict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coronaDistrict',
        ),
    ]
