# Generated by Django 3.2.6 on 2021-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0006_delete_coronadistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='coronaDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=10)),
                ('confirmed', models.IntegerField(default=0)),
            ],
        ),
    ]
