# Generated by Django 3.2.6 on 2021-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0007_coronadistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronadistrict',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
