# Generated by Django 3.2.6 on 2021-09-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0008_coronadistrict_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccinepercorona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='vaccineRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
